### PR TITLE
Support additional C2C TLS listener

### PR DESCRIPTION
**Pull request by mariash**
Parse multiple listeners for the cluster and generate separate
certificate for Nginx

[#180173340](https://www.pivotaltracker.com/story/show/180173340)

### CODE REVIEW

**Comment by aemengo** [comment]
Considering that container-to-container networking is not supported on windows nodes and this repository is in maintenance, I'm against introducing changes like this - for fear of introducing a regression. What do you think?

**Comment by aminjam** [comment]
@aemengo I think that the problem we are having is that after [this pr](https://github.com/cloudfoundry/executor/pull/58), executor now generates a different `envoy.yaml` with TLS C2C supported at the core of it. This is leading to a situation where envoy-nginx process can't start up properly without this change. 

@mariash We should probably ensure backward-compatibility in the case this release is used with the default `envoy.yaml` (without C2C). I didn't see any tests that was exercising the default path, but maybe I missed it.

**Comment by aemengo** [comment]
Is there an environment we can use to validate these changes?

**Comment by aminjam** [comment]
Yeah, I believe the problem is occurring in our pipelines after deploying develop branch of diego-release. If you replace your released version of diego with develop branch you will likely see the error.

**Comment by mariash** [comment]
@aemengo Sorry I didn't include enough information in the PR description. I was not sure who owns this repo. 

The old implementation of the envoy-nginx assumed there is only one listener for the server which translated for one server for one upstream in nginx config. The latest update to executor adds another listener to envoy config which proxies port 61443 (in addition to 61001 that is used by Gorouter) to application port 8080. When parser generated nginx config this resulted in nginx config having only one server definition for either Gorouter 61001 port or C2C TLS port 61443 and so breaking the default Gorouter port. The code now parses the envoy config more generically and will generate nginx server for each defined envoy listener. Please let me know if there are still concerns.

@aminjam thanks for pointing out to backwards compatibility. I brought back the old fixture and added tests for it.

**Pull request merged**
